baseURL: "https://jluo41.github.io/"
title: Junjie Luo
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
        - name: Research
          url: research/
          weight: 4
        - name: Collaboration
          url: collaboration/
          weight: 5

params:
    description: "Junjie Luo is a PhD candidate in Health Science Informatics at Johns Hopkins School of Medicine. His research focuses on healthcare AI using real-world data, foundation models, natural language processing, and multi-modal sensor data modeling."
    author: Junjie Luo
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Junjie Luo
          subtitle: "I am a PhD candidate in Health Science Informatics at Johns Hopkins School of Medicine. My research focuses on designing and developing healthcare AI using real-world data, with special emphasis on human factors and behaviors to enhance health and wellness. My work spans foundation models for healthcare, natural language processing of clinical text, and multi-modal sensor data modeling."
          imageUrl: "picture.jpeg"
          imageWidth: 440
          imageHeight: 300
          buttons:
            - name: About
              url: about/
            - name: Papers
              url: papers/
            - name: Teaching
              url: teaching/
            - name: Research
              url: research/
            - name: Collaboration
              url: collaboration/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:jluo41@jhu.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=csSHTp4AAAAJ&hl=en
        - name: GitHub
          url: https://github.com/jluo41
        - name: LinkedIn
          url: https://www.linkedin.com/in/junjie-luo/
        - name: Twitter
          url: https://twitter.com/junjie_luo_

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Junjie Luo"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2